=== api-evangelist/amazon-api-gateway/json-schema/amazon-api-gateway-methodsetting-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MethodSetting",
  "type": "object",
  "properties": {
    "metricsEnabled": {
      "type": "boolean"
    },
    "loggingLevel": {
      "type": "string",
      "enum": [
        "OFF",
        "ERROR",
        "INFO"
      ]
    },
    "dataTraceEnabled": {
      "type": "boolean"
    },
    "throttlingBurstLimit": {
      "type": "integer"
    },
    "throttlingRateLimit": {
      "type": "number"
    },
    "cachingEnabled": {
      "type": "boolean"
    },
    "cacheTtlInSeconds": {
      "type": "integer"
    },
    "cacheDataEncrypted": {
      "type": "boolean"
    },
    "requireAuthorizationForCacheControl": {
      "type": "boolean"
    },
    "unauthorizedCacheControlHeaderStrategy": {
      "type": "string",
      "enum": [
        "FAIL_WITH_403",
        "SUCCEED_WITH_RESPONSE_HEADER",
        "SUCCEED_WITHOUT_RESPONSE_HEADER"
      ]
    }
  }
}

=== api-evangelist/amazon-api-gateway/examples/amazon-api-gateway-methodsetting-example.json
{
  "metricsEnabled": true,
  "loggingLevel": "OFF",
  "dataTraceEnabled": true,
  "throttlingBurstLimit": 1,
  "cachingEnabled": true,
  "cacheTtlInSeconds": 1,
  "cacheDataEncrypted": true,
  "requireAuthorizationForCacheControl": true,
  "unauthorizedCacheControlHeaderStrategy": "FAIL_WITH_403"
}
