=== api-evangelist/amazon-api-gateway/json-schema/amazon-api-gateway-createauthorizerrequest-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CreateAuthorizerRequest",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the authorizer."
    },
    "type": {
      "type": "string",
      "enum": [
        "TOKEN",
        "REQUEST",
        "COGNITO_USER_POOLS"
      ]
    },
    "providerARNs": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "authType": {
      "type": "string"
    },
    "authorizerUri": {
      "type": "string"
    },
    "authorizerCredentials": {
      "type": "string"
    },
    "identitySource": {
      "type": "string"
    },
    "identityValidationExpression": {
      "type": "string"
    },
    "authorizerResultTtlInSeconds": {
      "type": "integer"
    }
  },
  "required": [
    "name",
    "type"
  ]
}

=== api-evangelist/amazon-api-gateway/examples/amazon-api-gateway-createauthorizerrequest-example.json
{
  "name": "example-name",
  "type": "TOKEN",
  "providerARNs": [],
  "authType": "example-authType",
  "authorizerUri": "example-authorizerUri",
  "authorizerCredentials": "example-authorizerCredentials",
  "identitySource": "example-identitySource",
  "identityValidationExpression": "example-identityValidationExpression",
  "authorizerResultTtlInSeconds": 1
}
