=== api-evangelist/amazon-api-gateway/json-schema/amazon-api-gateway-createdomainnamerequest-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CreateDomainNameRequest",
  "type": "object",
  "properties": {
    "domainName": {
      "type": "string"
    },
    "certificateName": {
      "type": "string"
    },
    "certificateBody": {
      "type": "string"
    },
    "certificatePrivateKey": {
      "type": "string"
    },
    "certificateChain": {
      "type": "string"
    },
    "certificateArn": {
      "type": "string"
    },
    "regionalCertificateName": {
      "type": "string"
    },
    "regionalCertificateArn": {
      "type": "string"
    },
    "endpointConfiguration": {
      "$ref": "#/definitions/EndpointConfiguration"
    },
    "tags": {
      "type": "object"
    },
    "securityPolicy": {
      "type": "string",
      "enum": [
        "TLS_1_0",
        "TLS_1_2"
      ]
    },
    "mutualTlsAuthentication": {
      "type": "object",
      "properties": {
        "truststoreUri": {
          "type": "string"
        },
        "truststoreVersion": {
          "type": "string"
        }
      }
    }
  },
  "required": [
    "domainName"
  ]
}

=== api-evangelist/amazon-api-gateway/examples/amazon-api-gateway-createdomainnamerequest-example.json
{
  "domainName": "example-domainName",
  "certificateName": "example-certificateName",
  "certificateBody": "example-certificateBody",
  "certificatePrivateKey": "example-certificatePrivateKey",
  "certificateChain": "example-certificateChain",
  "certificateArn": "example-certificateArn",
  "regionalCertificateName": "example-regionalCertificateName",
  "regionalCertificateArn": "example-regionalCertificateArn",
  "endpointConfiguration": "example-endpointConfiguration",
  "tags": {},
  "securityPolicy": "TLS_1_0",
  "mutualTlsAuthentication": {}
}
